language: cpp

compiler:
 - gcc

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq swig libeigen3-dev

before_script:
 - mkdir build
 - cd build
 - env
 - cmake -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DCMAKE_INSTALL_PREFIX=~ ..

script:
 - make
 - make install
 - make test
