language: cpp

compiler:
 - gcc

python:
 - "2.5"
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq swig libeigen3-dev

before_script:
 - mkdir build
 - cd build
 - cmake -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DPYTHON_EXECUTABLE=$VIRTUAL_ENV/bin/python -DPYTHON_INCLUDE_PATH=$VIRTUAL_ENV/include/python$TRAVIS_PYTHON_VERSION -DPYTHON_LIBRARY=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/config/libpython$TRAVIS_PYTHON_VERSION.so ..

script:
 - make
 - make install
 - make test
