language: cpp

compiler:
 - gcc

python:
 - "2.5"
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"

before_install:
 - sudo apt-get update -qq

before_script:
 - mkdir build
 - cd build
 - cmake -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON ..

script:
 - make
 - make install
 - make test
