language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq swig libeigen3-dev libperl-dev mono-gmcs php5-dev

before_script:
 - mkdir build
 - cd build
 - cmake -DPYTHON_BINDINGS=ON  -DPHP_BINDINGS=ON -DPERL_BINDINGS=ON -DJAVA_BINDINGS=ON -DCSHARP_BINDINGS=ON  -DRUN_SWIG=ON -DCSHARP_EXECUTABLE=gmcs ..

script:
 - make
 - make test
