language: python

python:
 - "3.3"

env:
 - CC=clang CXX=clang++
 - CC=gcc CXX=g++

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq swig libeigen3-dev libperl-dev mono-gmcs php5-dev

before_script:
 - mkdir build
 - cd build
 - env
 - cmake -DALL_BINDINGS=ON -DRUN_SWIG=ON -DCSHARP_EXECUTABLE=gmcs ..

script:
 - make
 - make test
